---
groups:
- name: test-and-release
  jobs:
  - bump-deps
  - test-unit
  - publish-multidigest-binary

- name: docker-images
  jobs:
  - build-bosh-utils-image

- name: all
  jobs:
  - test-unit
  - publish-multidigest-binary
  - build-bosh-utils-image
  - bump-deps

jobs:
  - name: bump-deps
    serial: true
    plan:
      - in_parallel:
        - get: weekly
          trigger: true
        - get: bosh-utils
        - get: golang-release
        - get: bosh-utils-image
      - task: bump-deps
        file: golang-release/ci/tasks/shared/bump-deps.yml
        input_mapping:
          input_repo: bosh-utils
        output_mapping:
          output_repo: bumped-bosh-utils
      - in_parallel:
        - task: test-unit
          input_mapping:
            bosh-utils: bumped-bosh-utils
          file: bosh-utils/ci/tasks/test-unit.yml
          image: bosh-utils-image
        - task: test-unit-windows
          input_mapping:
            bosh-utils: bumped-bosh-utils
          file: bosh-utils/ci/tasks/test-unit-windows.yml
          tags:
            - windows-nimbus
      - put: bosh-utils
        inputs: detect
        params:
          repository: bumped-bosh-utils

  - name: test-unit
    serial: true
    plan:
      - in_parallel:
        - get: bosh-utils
          trigger: true
        - get: bosh-utils-registry-image
          trigger: true
        - get: version-semver
          params: {bump: patch}
        - get: bosh-utils-image
      - in_parallel:
        - task: test-unit
          image: bosh-utils-image
          file: bosh-utils/ci/tasks/test-unit.yml
        - task: test-unit-windows
          file: bosh-utils/ci/tasks/test-unit-windows.yml
          tags:
            - windows-nimbus
      - put: bosh-utils-commit-status
        inputs: detect
        params:
          state: success
          commit: bosh-utils
      - put: bosh-utils-promoted
        inputs: detect
        params:
          repository: bosh-utils
          tag_prefix: "v"
          tag: version-semver/version
      - put: version-semver
        inputs: detect
        params: { file: version-semver/version }

  - name: publish-multidigest-binary
    serial: true
    plan:
      - get: bosh-utils
        trigger: true
        passed: [test-unit]
      - get: bosh-utils-registry-image
        trigger: true
        passed: [test-unit]
      - get: version-semver
        passed: [test-unit]
      - task: build-multidigest-binary-linux
        file: bosh-utils/ci/tasks/build-multidigest-binary.yml
        output_mapping: { out: compiled-linux }
        params:
          GOOS: linux
          GOARCH: amd64
      - put: release-bucket-linux
        inputs: detect
        params: {file: compiled-linux/verify-multidigest-*-linux-amd64}

  - name: build-bosh-utils-image
    serial: true
    plan:
      - get: bosh-utils-dockerfiles
        trigger: true
      - get: bosh-golang-release-image
        trigger: true
      - put: bosh-utils-image
        inputs: detect
        params:
          build: "bosh-utils-dockerfiles/ci/docker"
        get_params:
          skip_download: true

resources:
  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [Saturday]

  - name: bosh-utils
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-utils.git
      branch: develop
      username: bosh-admin-bot
      password: ((github_public_repo_token))

  - name: bosh-utils-promoted
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-utils.git
      branch: master
      username: bosh-admin-bot
      password: ((github_public_repo_token))

  - name: bosh-utils-commit-status
    type: github-status
    source:
      repository: cloudfoundry/bosh-utils
      access_token: ((github_read_write_token))
      branch: develop
      context: ci/unit-tests

  - name: bosh-utils-dockerfiles
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-utils.git
      branch: develop
      username: bosh-admin-bot
      password: ((github_public_repo_token))
      paths:
      - "ci/docker"

  - name: golang-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

  - name: release-bucket-linux
    type: gcs
    source:
      regexp: verify-multidigest/verify-multidigest-(.*)-linux-amd64
      bucket: bosh-director-pipeline
      json_key: ((cloud-foundry-gcp-credentials))

  - name: version-semver
    type: semver
    source:
      driver: git
      uri: https://github.com/cloudfoundry/bosh-utils.git
      username: bosh-admin-bot
      password: ((github_public_repo_token))
      branch: release-semver
      file: verify-multidigest/VERSION
      initial_version: '0.0.500'

  - name: bosh-utils-image
    type: docker-image
    source:
      repository: bosh/utils
      username: ((docker.username))
      password: ((docker.password))

  - name: bosh-utils-registry-image
    type: registry-image
    source:
      repository: bosh/utils
      username: ((docker.username))
      password: ((docker.password))

  - name: bosh-golang-release-image
    type: registry-image
    source:
      repository: bosh/golang-release
      username: ((docker.username))
      password: ((docker.password))

resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master
  - name: semver
    type: docker-image
    source:
      repository: concourse/semver-resource
      tag: 1.6
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource